/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caixaeletronico_ui;

import javax.swing.JOptionPane;
/**
 *
 * @author novo
 */
public class Interface extends javax.swing.JFrame {

    private Conta objConta = null;
    
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        this.objConta = new Conta();
        txtSaida.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntSaldo = new javax.swing.JButton();
        bntDeposito = new javax.swing.JButton();
        bntSaque = new javax.swing.JButton();
        bntSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSaida = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bntSaldo.setText("SALDO");
        bntSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSaldoActionPerformed(evt);
            }
        });

        bntDeposito.setText("DEPÓSITO");
        bntDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDepositoActionPerformed(evt);
            }
        });

        bntSaque.setText("SAQUE");
        bntSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSaqueActionPerformed(evt);
            }
        });

        bntSair.setText("SAIR");
        bntSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSairActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtSaida);
        txtSaida.getAccessibleContext().setAccessibleName("txtSaida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntSair, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(bntSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(bntDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(bntSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(bntSair, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSaldoActionPerformed
        
        //System.out.println("SALDO: " + this.objConta.verificarSaldo()) ;
        txtSaida.setText("SALDO:" + this.objConta.verificarSaldo());
        
    }//GEN-LAST:event_bntSaldoActionPerformed

    private void bntSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSaqueActionPerformed
        
        float valorSaque =  Float.parseFloat(JOptionPane.showInputDialog("INFORME UM VALOR DE SAQUE"));

        if (valorSaque <= this.objConta.saldo){
        objConta.realizarSaque(valorSaque);

        txtSaida.setText("SALDO: " + this.objConta.verificarSaldo());
        
        }else if (valorSaque > this.objConta.saldo){
        
            JOptionPane.showMessageDialog(null, "SAQUE INVÁLIDO! SAQUE UM VALOR QUE O SENHOR(A) TENHA EM SUA CONTA!");
            
        }
    }//GEN-LAST:event_bntSaqueActionPerformed

    private void bntDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDepositoActionPerformed
         float valorDeposito =  Float.parseFloat(JOptionPane.showInputDialog("INFORME UM VALOR DE DEPÓSITO"));
         
       if (valorDeposito > 0){
        objConta.realizarDeposito(valorDeposito);

        txtSaida.setText("SALDO: " + this.objConta.verificarSaldo());
       }else if (valorDeposito < 0){
       
           JOptionPane.showMessageDialog(null, "DEPOSITO INVÁLIDO! DEPOSITE UM VALOR POSITIVO!");
           
       }
    }//GEN-LAST:event_bntDepositoActionPerformed

    private void bntSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSairActionPerformed
        
        System.exit(0);
        
    }//GEN-LAST:event_bntSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntDeposito;
    private javax.swing.JButton bntSair;
    private javax.swing.JButton bntSaldo;
    private javax.swing.JButton bntSaque;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane txtSaida;
    // End of variables declaration//GEN-END:variables
}
